services:
  waves-server-sql:
    image: mysql:8.4.0-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: waves
    volumes:
    - waves-server-sql:/var/lib/mysql
    networks:
    - wavesmp
    extra_hosts:
    - "host.docker.internal:192.168.32.1"
    # May need to expose sql port to run ad hoc queries
    # ports:
    # - '127.0.0.1:3306:3306'

  waves-server-rust:
    image: osoriano/waves-server-rust:latest
    environment:
      RUST_LOG: info
    volumes:
    - './packages/waves-server-rust/config.json:/config.json'
    networks:
    - wavesmp
    extra_hosts:
    - "host.docker.internal:192.168.32.1"
    depends_on:
    - waves-server-sql

  waves-client-web:
    image: osoriano/waves-client-web:latest
    networks:
    - wavesmp
    extra_hosts:
    - "host.docker.internal:192.168.32.1"
    depends_on:
    - waves-server-rust
    ports:
    - '127.0.0.1:81:80'
    volumes:
    - './packages/waves-client-web/rootfs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf'
    - './packages/waves-client-web/rootfs/etc/nginx/sites/:/etc/nginx/sites/'

volumes:
  waves-server-sql:
    external: true
    name: wavesmp_waves-server-sql

# Use a stable address for convenience
networks:
  wavesmp:
    ipam:
      config:
      - subnet: 192.168.32.0/20
        gateway: 192.168.32.1
