services:
  waves-server-sql:
    image: mysql:8.4.0-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: waves
    volumes:
      - waves-server-sql:/var/lib/mysql
    networks:
      - wavesmp
    # May need to expose sql port to run ad hoc queries
    # ports:
    # - '127.0.0.1:3306:3306'

  waves-server-rust:
    image: osoriano/waves-server-rust:latest
    environment:
      RUST_LOG: info
    volumes:
      - './packages/waves-server-rust/config.json:/config.json'
    networks:
      - wavesmp
    depends_on:
      - waves-server-sql

  waves-client-web-builder:
    image: node:21.7.3-bookworm
    user: node
    environment:
      NODE_ENV: development
    volumes:
      - './:/repo'
    working_dir: /repo
    networks:
      - wavesmp
    depends_on:
      - waves-server-rust
    entrypoint: bash
    command:
    - '-c'
    - |
        set -o errexit
        set -o pipefail
        set -o nounset

        cp packages/waves-client-web/src/index.html \
           packages/waves-client-web/src/privacy.html \
           packages/waves-client-web/src/favicon.ico \
           packages/waves-client-web/vendor/aws-sdk-2.268.1.min.js \
           packages/waves-client-web/build

        npm run watch

  waves-client-web:
    image: nginx:1.25.5-bookworm
    networks:
    - wavesmp
    depends_on:
      - waves-server-rust
      - waves-client-web-builder
    ports:
    - '127.0.0.1:81:80'
    volumes:
    - './packages/waves-client-web/build:/srv/http'
    - './packages/waves-client-web/rootfs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf'
    - './packages/waves-client-web/rootfs/etc/nginx/sites/:/etc/nginx/sites/'
    environment:
      NODE_ENV: development

volumes:
  waves-server-sql:
    external: true
    name: wavesmp_waves-server-sql

# Use a stable address for convenience
networks:
  wavesmp:
    ipam:
      config:
        - subnet: 192.168.32.0/20
          gateway: 192.168.32.1
