apiVersion: v1
kind: Service
metadata:
  namespace: wavesmusicplayer
  name: waves-server-rust
spec:
  ports:
  - port: 16244
    name: ws
  - port: 16245
    name: http
  selector:
    app: waves-server-rust
  type: ClusterIP
