/*
 * Constants to be replaced in source files
 */


// Old light theme
// MAIN_THEME_COLOR: '#4AA3DF',
// BODY_COLOR_OLD: '#555',
// BODY_BACKGROUND_COLOR_OLD: '#f0f0f0',

const grayHover = '#434857'
const gray = '#999999'
const lightGray = '#f5f5f5'
const grayBackground = '#e6e6e6'
const white = '#fff'

module.exports = {

  MENUBAR_HEIGHT: '65px',
  SIDEBAR_WIDTH: '70px',
  PLAYLISTBAR_WIDTH: '140px',
  TRACKSLIDER_WIDTH: '5px',

  DRAG_BOX_WIDTH: '180',
  DRAG_BOX_HEIGHT: '50',
  DRAG_BOX_BORDER_RADIUS: '5',
  DRAG_BOX_BORDER_COLOR: '#19b698',
  DRAG_BOX_BORDER_WIDTH: '5',

  DARK_DRAG_BOX_BACKGROUND_COLOR: '#2b5757',
  DARK_DRAG_BOX_TEXT_COLOR: white,
  LIGHT_DRAG_BOX_BACKGROUND_COLOR: '#d6fff9',
  LIGHT_DRAG_BOX_TEXT_COLOR: '#333',

  DARK_BODY_COLOR: '#252830',
  DARK_TEXT_COLOR: gray,

  DARK_TITLE_COLOR: white,
  DARK_MODAL_TITLE_COLOR: gray,

  DARK_MENUBAR_COLOR: '#252830',

  DARK_SEPARATOR_COLOR: grayHover,

  DARK_SIDEBAR_COLOR: '#30343E',
  DARK_SIDEBAR_COLOR_HOVER: grayHover,
  DARK_SIDEBAR_COLOR_ACTIVE_ICON: '#6F7890',
  DARK_SIDEBAR_ICONS_COLOR: 'hsla(0,0%,100%,.7)',
  DARK_SIDEBAR_ICONS_COLOR_HOVER: white,

  DARK_MODAL_CLOSE_BTN_BORDER: gray,
  DARK_MODAL_CLOSE_BTN_HOVER_BORDER_COLOR: '#7F7A7A',
  DARK_MODAL_CLOSE_BTN_HOVER_COLOR: lightGray,

  DARK_TABLE_COLOR_HOVER: grayHover,
  DARK_INPUT_BACKGROUND_COLOR: grayHover,
  DARK_INPUT_ICON_COLOR: '#ccc',

  DARK_BUTTON_PRIMARY_COLOR: '#1997c6',

  DARK_SELECTED_COLOR: '#2B4157',
  DARK_SELECTED_COLOR_BORDER: '#42A5F5',

  DARK_TOAST_BACKGROUND_COLOR: '#e6e6e6',
  DARK_TOAST_SUCCESS_COLOR: '#19b698',
  DARK_TOAST_ERROR_COLOR: '#df3e3e',
  DARK_TOAST_TEXT_COLOR: '#333',

  DARK_MODAL_BACKGROUND_COLOR: grayBackground,
  DARK_UPLOAD_BORDER_COLOR: grayBackground,

  DARK_DROPDOWN_COLOR: grayBackground,
  DARK_DROPDOWN_COLOR_LIGHT: lightGray,
  DARK_DROPDOWN_SELECTED_BORDER_COLOR: '#adadad',

  DARK_TRACKSLIDER_BACKGROUND_COLOR: '#F0F0F0',
  DARK_TRACKSLIDER_BORDER_COLOR: '#ccc',

  DARK_ACTIVE_PAGE_BACKGROUND_COLOR: gray,
  DARK_ACTIVE_PAGE_COLOR: '#252830',

  LIGHT_BODY_COLOR: white,
  LIGHT_TEXT_COLOR: '#333',

  LIGHT_TITLE_COLOR: '#333',
  LIGHT_MODAL_TITLE_COLOR: '#333',

  LIGHT_SEPARATOR_COLOR: '#eee',

  LIGHT_MENUBAR_COLOR: white,

  LIGHT_SIDEBAR_COLOR: '#eee',
  LIGHT_SIDEBAR_COLOR_HOVER: '#f7f7f7',
  LIGHT_SIDEBAR_COLOR_ACTIVE_ICON: 'hsla(0,0%,0%,.65)',
  LIGHT_SIDEBAR_ICONS_COLOR: 'hsla(0,0%,0%,.7)',
  LIGHT_SIDEBAR_ICONS_COLOR_HOVER: 'hsla(0,0%,0%,.6)',

  LIGHT_MODAL_CLOSE_BTN_BORDER: gray,
  LIGHT_MODAL_CLOSE_BTN_HOVER_BORDER_COLOR: '#7F7A7A',
  LIGHT_MODAL_CLOSE_BTN_HOVER_COLOR: lightGray,

  LIGHT_TABLE_COLOR_HOVER: '#f7f7f7',
  LIGHT_INPUT_BACKGROUND_COLOR: '#eee',
  LIGHT_INPUT_ICON_COLOR: 'hsla(0,0%,0%,.7)',

  LIGHT_BUTTON_PRIMARY_COLOR: '#1997c6',

  LIGHT_SELECTED_COLOR: '#D9EDFD',
  LIGHT_SELECTED_COLOR_BORDER: '#42A5F5',

  LIGHT_TOAST_BACKGROUND_COLOR: '#e6e6e6',
  LIGHT_TOAST_SUCCESS_COLOR: '#19b698',
  LIGHT_TOAST_ERROR_COLOR: '#df3e3e',
  LIGHT_TOAST_TEXT_COLOR: '#333',

  LIGHT_MODAL_BACKGROUND_COLOR: grayBackground,
  LIGHT_UPLOAD_BORDER_COLOR: grayBackground,

  LIGHT_DROPDOWN_COLOR: grayBackground,
  LIGHT_DROPDOWN_COLOR_LIGHT: lightGray,
  LIGHT_DROPDOWN_SELECTED_BORDER_COLOR: '#adadad',

  LIGHT_TRACKSLIDER_BACKGROUND_COLOR: '#F0F0F0',
  LIGHT_TRACKSLIDER_BORDER_COLOR: '#ccc',

  LIGHT_ACTIVE_PAGE_BACKGROUND_COLOR: '#eee',
  LIGHT_ACTIVE_PAGE_COLOR: '#333',
}

